import type { KnowledgeObject, Manifest, PackSchema } from "../core/protocol/types.js";

/**
 * Static description of an extractor — surfaced by `akp extractors list` and
 * used by the refresh use case to disambiguate when multiple extractors are
 * registered. The `id` is the identity AKP uses to decide which existing
 * canonical objects an extractor "owns" on subsequent refreshes (an object's
 * `provenance.generated_by` matches `${id}` exactly or starts with `${id}:`).
 */
export interface ExtractorDescriptor {
  id: string;
  description: string;
  produces_types: readonly string[];
}

/**
 * Read-only inputs the refresh use case hands to an extractor. The extractor
 * must NOT mutate the manifest or schema; it should treat them as a frozen
 * view of the project to extract knowledge against.
 */
export interface SourceExtractorContext {
  rootDir: string;
  manifest: Manifest;
  schema: PackSchema;
}

/**
 * Plug-in surface for extracting knowledge objects from an artifact. An
 * extractor implementation is the heart of a domain pack — it walks the
 * artifact (a TypeScript repo, a Java repo, a docs site, ...) and emits
 * typed KnowledgeObjects whose `provenance.generated_by` identifies this
 * extractor.
 *
 * Contract for emitted objects:
 *   - `provenance.generated_by` MUST equal `${descriptor.id}` exactly or
 *     start with `${descriptor.id}:` (sub-namespace allowed for the
 *     extractor's internal versioning, e.g. "ts-repo:v1").
 *   - `provenance.generated_at` and `freshness.last_verified` MUST be
 *     valid ISO 8601 strings.
 *   - Each object MUST conform to `knowledgeObjectSchema` and the project's
 *     pack schema; the refresh use case will reject the entire run if any
 *     emitted object fails validation.
 */
export interface SourceExtractor {
  describe(): ExtractorDescriptor;
  extract(context: SourceExtractorContext): AsyncIterable<KnowledgeObject>;
}

/**
 * True if `object` was generated by the extractor with `extractorId`. The
 * refresh use case uses this to partition canonical objects into "owned by
 * this extractor" (replaced on refresh) vs "everything else" (preserved).
 */
export function isOwnedByExtractor(object: KnowledgeObject, extractorId: string): boolean {
  const generatedBy = object.provenance.generated_by;
  return generatedBy === extractorId || generatedBy.startsWith(`${extractorId}:`);
}
